export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR'

export const GET_TRENDING = 'GET_TRENDING';
export const TRENDING_ERROR = 'TRENDING_ERROR'

export const GET_TOPRATED = 'GET_TOPRATED';
export const TOPRATED_ERROR = 'TOPRATED_ERROR'

export const GET_NOWPLAYING = 'GET_NOWPLAYING';
export const NOWPLAYING_ERROR = 'NOWPLAYING_ERROR'

export const GET_POPULAR = 'GET_POPULAR';
export const POPULAR_ERROR = 'POPULAR_ERROR'
